---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
---


```{r}
Bikes <- read.csv("~/Desktop/Final+Bike+Collision+Database.csv", sep = ",", header = TRUE, na.strings=c("", "NA"), stringsAsFactors=FALSE)
# Names of columns
colnames(Bikes)
library(dplyr)
Bikes$TYPE <- recode(Bikes$TYPE, BR = "Bicycle-Related ", BVA = "Bike vs. Auto", BVB="Bike vs. Bike", BVP="Bike vs. Pedestrian",CO="Cyclist Only")
Bikes <- within(Bikes, 
                   PlanningDi <- factor(PlanningDi, 
                                    levels=names(sort(table(PlanningDi))))) 
Bikes$HelmetDocu <- ifelse(Bikes$HelmetDocu == 1, 'Helmet', 'No Helmet')
base.no.na <- ggplot(na.omit(Bikes[Bikes$INJURED!=99,]), aes(x=PlanningDi))
full_graph <- base.no.na + geom_bar(aes(fill=as.factor(TYPE))) + theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 7)) + xlab("Neighborhoods") + labs(fill="Type of collision") + ggtitle("Types of collisions in each neighborhood")
full_graph
h <- full_graph + facet_wrap(~HelmetDocu) 
ggsave("h.png", path = "~/Desktop")
table(Bikes$HelmetDocu)
## Cleaning Data
# Checking for columns, which all their values are NA
colnames(Bikes)[apply(is.na(Bikes), 2, all)]

# Convert to Date format
library(lubridate)  
# IVS.SRT is the date on which the TF formally opened an investigation
To_Date <- mdy(Bikes$DATE)
Bikes$DATE <- as.Date(To_Date, format = "%Y-%m-%d")

library(ggplot2)
base.no.na <- ggplot(Bikes[!is.na(Bikes$WEATHER!=99) & Bikes$WEATHER !="",], aes(x=WEATHER)) 
g <- base.no.na + geom_bar(fill = "tan") + theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 9)) + 
  ggtitle("Number of bike collisions in different weather condistions") 
```

```{r}
d2 <- ggplot(na.omit(Bikes[Bikes$INJURED!=99,]), aes(RoadType)) + geom_bar(aes(fill = as.factor(INJURED))) + theme_bw() + ggtitle("Number of injured cyclists based on road types") + xlab("Road Types") + labs(fill = "Injured")
ggsave("d2.png", path = "~/Desktop")

dt <- Bikes %>% mutate(year = as.factor(format(Bikes$DATE, format = "%Y")), month = as.factor(format(Bikes$DATE, format = "%m")))
exp_dt <- dt[!is.na(dt$year),] %>% group_by(year, month) %>% summarize(number = n())
t2 <- ggplot(exp_dt[exp_dt$number!= 'NA',] , aes(y=number, x=year, alpha = number, fill = month, color = month)) + geom_bar(stat="identity") + ggtitle("Number of bike collisions by year") + xlab("Year") + ylab("Number of bike collisions") +theme_bw()+ theme(text = element_text(size=14))
ggsave("t2.png", path = "~/Desktop")

##remove missing values (99) from data##
base.no.na<-ggplot(Bikes[Bikes$INJURED!=99,], aes(x=Tavg))
base.no.na+geom_bar(aes(fill=as.factor(INJURED)), binwidth=0.5)
```


```{r}
str_detect(Bikes$WEATHER, "CLEAR")
Bikes$Clear<-as.numeric(str_detect(Bikes$WEATHER, "CLEAR"))
table(Bikes$Clear)
library(stringr)
Bikes$ClearNoPrecip <- ifelse(str_detect(Bikes$WEATHER, "CLEAR") & Bikes$PrecipTota == 0, 1, 0)
Bikes$Weekend<-ifelse(wday(ymd(Bikes$DATE))==1 | wday(ymd(Bikes$DATE))==7, 'Weekend', 'Weekday')
table(Bikes$Weekend)
base.no.na <- ggplot(na.omit(Bikes[Bikes$INJURED!=99,]), aes(x=Tavg))
full_graph<-base.no.na + geom_histogram(aes(fill=as.factor(INJURED)), binwidth=0.5) + scale_x_continuous("Average Temp.", limits = c(20,90), breaks = c(20,30,40,50,60,70,80,90)) + labs(fill = "INJURED")
h <- full_graph + facet_wrap(~Weekend) + theme_bw()
ggsave("h.png", path = "~/Desktop")
full_graph+facet_grid(Clear~Weekend)

```

```{r}
base <- ggplot(na.omit(Bikes[Bikes$GENDER!=99 & Bikes$ETHNICITY!=99,]), aes(x=ETHNICITY, y=AGE, fill=GENDER))+geom_bar(stat = 'summary') + theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, size = 7)) + ggtitle("Age, Ethnicity and Gender of cyclists")
ggsave("base.png", path = "~/Desktop")
```



